universe        = container
container_image = file:///staging/n/nkalthoff/surgvu26/surgvu26-train.sif
executable      = containers/gpu_check.sh
output = logs/gpu_check_$(Cluster).out
error  = logs/gpu_check_$(Cluster).err
log    = logs/gpu_check_$(Cluster).log
+WantStagingMount = true
request_gpus   = 1
require_gpus   = (DeviceName == "NVIDIA GeForce RTX 2080 Ti")
request_cpus   = 1
request_memory = 4GB
request_disk   = 4GB
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
queue 1
