#!/bin/bash
set -euo pipefail
# Generate and submit a DAG that scores a training arm once it finishes.
#
#   condor/dump_after.sh <cluster> <checkpoint.pt> <shards_dir> <label> [gpumem]
#
# WHY THIS EXISTS AS A SCRIPT. Twice tonight an arm was launched with nothing
# scheduled to evaluate it -- first the two dense-pool conversions, then the
# lr=1e-5 arm -- because the evaluator was wired into a DAG that was submitted
# before the arm existed. An arm that finishes at 04:00 and sits unscored has
# not finished. One command now attaches the evaluation at launch time, so the
# hole cannot reopen every time an ad-hoc arm is added.
#
# The gate waits on QUEUE MEMBERSHIP, not on the checkpoint file: a checkpoint
# is rewritten only on improving epochs, so "the file stopped changing" cannot
# be told apart from "the model stopped improving".

CLUSTER="${1:?usage: dump_after.sh <cluster> <checkpoint> <shards> <label> [gpumem]}"
CHECKPOINT="${2:?}"
SHARDS="${3:?}"
LABEL="${4:?}"
# 10000, not 16000. A dump is forward passes over 8 frames -- a couple of GB
# at most -- and at 16 GB it competes with the training arms for the same
# slots. Measured at 00:03 with six arms running: "0 slots match and are
# willing to run your job" at 16 GB, 22 that would match if drained. The
# evaluation should never be the thing waiting on the experiment.
GPUMEM="${5:-10000}"
# Anything after the gpumem argument is passed through to the dump script --
# notably --aggregate probs, which is required whenever the result will be
# compared against the 2D reference. The 2D path averages PROBABILITIES; the
# default here averages logits because that is how the arms TRAIN. Scoring one
# way and comparing to the other is worth 0.0145 and cost most of an hour to
# diagnose.
shift 5 2>/dev/null || shift $#
EXTRA="$*"

DAG="condor/generated/dump_${LABEL}.dag"
mkdir -p condor/generated logs

cat > "$DAG" <<INNER
# GENERATED by condor/dump_after.sh -- edits here are overwritten.
# Scores cluster ${CLUSTER} (${CHECKPOINT}) once it leaves the queue.

JOB gate condor/gate_cluster.sub
JOB dump condor/train_temporal.sub

VARS gate clusters="${CLUSTER}"
VARS dump node="dump${LABEL}" memory="32GB" gpumem="${GPUMEM}" \\
  script="scripts/dump_temporal_probs.py" \\
  args="--checkpoint ${CHECKPOINT} --shards ${SHARDS} ${EXTRA} --out /staging/n/nkalthoff/surgvu26/dumps/temporal_${LABEL}.npz"

PARENT gate CHILD dump
RETRY dump 1
INNER

echo "wrote $DAG"
condor_submit_dag "$DAG" | grep -E "submitted to cluster|ERROR"
